# Generated by Django 4.2.8 on 2023-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateTimeField(),
        ),
    ]
