# Generated by Django 4.2.8 on 2023-12-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_api', '0003_user_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notes',
        ),
    ]
